In [1]:
import pandas as pd
import numpy as np 
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
import nltk
from nltk.corpus import stopwords
import re
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer 
from nltk.stem.porter import PorterStemmer
from nltk.corpus import wordnet
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\const\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [2]:
train = pd.read_csv('train.csv', encoding = "utf-8")

In [3]:
train

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

Cleaning to be done: 
-@ + following (until the space) 

-Check avec un dictionnaire ? 

-Retirer les nombres (heure) -> Entity extraction

-Drop colum keyword and location

In [4]:
train["text"]=train["text"].str.lower()

In [5]:
trainS = train
trainS.head(20)

,id,keyword,location,text,target
0,1,NaN,NaN,our deeds are the reason of this #earthquake m...,1
1,4,NaN,NaN,forest fire near la ronge sask. canada,1
2,5,NaN,NaN,all residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,just got sent this photo from ruby #alaska as ...,1
5,8,NaN,NaN,#rockyfire update => california hwy. 20 closed...,1
6,10,NaN,NaN,#flood #disaster heavy rain causes flash flood...,1
7,13,NaN,NaN,i'm on top of the hill and i can see a fire in...,1
8,14,NaN,NaN,there's an emergency evacuation happening now ...,1
9,15,NaN,NaN,i'm afraid that the tornado is coming to our a...,1
10,16,NaN,NaN,three people died from the heat wave so far,1
11,17,NaN,NaN,haha south tampa is getting flooded hah- wait ...,1
12,18,NaN,NaN,#raining #flooding #florida #tampabay #tampa 1...,1
13,19,NaN,NaN,#flood in bago myanmar #we arrived bago,1
14,20,NaN,NaN,damage to school bus on 80 in multi car crash ...,1
15,23,NaN,NaN,what's up man?,0
16,24,NaN,NaN,i love fruits,0
17,25,NaN,NaN,summer is lovely,0
18,26,NaN,NaN,my car is so fast,0
19,28,NaN,NaN,what a goooooooaaaaaal!!!!!!,0

In [6]:
Contractions = {
"ain't": "is not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he'll've": "he he will have",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how is",
"I'd": "I would",
"I'd've": "I would have",
"I'll": "I will",
"I'll've": "I will have",
"I'm": "I am",
"I've": "I have",
"i'd": "i would",
"i'd've": "i would have",
"i'll": "i will",
"i'll've": "i will have",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she would",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there would",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they would",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what'll've": "what will have",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where is",
"where've": "where have",
"who'll": "who will",
"who'll've": "who will have",
"who's": "who is",
"who've": "who have",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you would",
"you'd've": "you would have",
"you'll": "you will",
"you'll've": "you will have",
"you're": "you are",
"you've": "you have"
}

In [7]:
def data_text_preprocess(total_text):
        
        total_text = re.sub('http\S+',' ', str(total_text))
        total_test = re.sub('https\S+',' ', str(total_text))
        total_text = re.sub('\@\S+',' ', str(total_text))
        total_text = re.sub('\#',' ', str(total_text))
        total_text = re.sub('[^a-zA-Z\'\n]', ' ', str(total_text))
       
        return total_text

In [8]:
trainS['text'] = trainS['text'].map(data_text_preprocess)
trainS.head(20)

,id,keyword,location,text,target
0,1,NaN,NaN,our deeds are the reason of this earthquake m...,1
1,4,NaN,NaN,forest fire near la ronge sask canada,1
2,5,NaN,NaN,all residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,people receive wildfires evacuation or...,1
4,7,NaN,NaN,just got sent this photo from ruby alaska as ...,1
5,8,NaN,NaN,rockyfire update california hwy closed...,1
6,10,NaN,NaN,flood disaster heavy rain causes flash flood...,1
7,13,NaN,NaN,i'm on top of the hill and i can see a fire in...,1
8,14,NaN,NaN,there's an emergency evacuation happening now ...,1
9,15,NaN,NaN,i'm afraid that the tornado is coming to our a...,1
10,16,NaN,NaN,three people died from the heat wave so far,1
11,17,NaN,NaN,haha south tampa is getting flooded hah wait ...,1
12,18,NaN,NaN,raining flooding florida tampabay tampa ...,1
13,19,NaN,NaN,flood in bago myanmar we arrived bago,1
14,20,NaN,NaN,damage to school bus on in multi car crash ...,1
15,23,NaN,NaN,what's up man,0
16,24,NaN,NaN,i love fruits,0
17,25,NaN,NaN,summer is lovely,0
18,26,NaN,NaN,my car is so fast,0
19,28,NaN,NaN,what a goooooooaaaaaal,0

In [9]:
 def decontraction(total_text):
        
        for i in Contractions:
            total_text = total_text.replace( i, Contractions.get(i))
        
        return total_text

In [10]:
trainS['text'] = trainS['text'].map(decontraction)
trainS.head(20)

,id,keyword,location,text,target
0,1,NaN,NaN,our deeds are the reason of this earthquake m...,1
1,4,NaN,NaN,forest fire near la ronge sask canada,1
2,5,NaN,NaN,all residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,people receive wildfires evacuation or...,1
4,7,NaN,NaN,just got sent this photo from ruby alaska as ...,1
5,8,NaN,NaN,rockyfire update california hwy closed...,1
6,10,NaN,NaN,flood disaster heavy rain causes flash flood...,1
7,13,NaN,NaN,i am on top of the hill and i can see a fire i...,1
8,14,NaN,NaN,there is an emergency evacuation happening now...,1
9,15,NaN,NaN,i am afraid that the tornado is coming to our ...,1
10,16,NaN,NaN,three people died from the heat wave so far,1
11,17,NaN,NaN,haha south tampa is getting flooded hah wait ...,1
12,18,NaN,NaN,raining flooding florida tampabay tampa ...,1
13,19,NaN,NaN,flood in bago myanmar we arrived bago,1
14,20,NaN,NaN,damage to school bus on in multi car crash ...,1
15,23,NaN,NaN,what is up man,0
16,24,NaN,NaN,i love fruits,0
17,25,NaN,NaN,summer is lovely,0
18,26,NaN,NaN,my car is so fast,0
19,28,NaN,NaN,what a goooooooaaaaaal,0

In [11]:
def get_wordnet_pos(word):
   
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}

    return tag_dict.get(tag, wordnet.NOUN)

In [12]:
lemmatizer = WordNetLemmatizer()

def lemmatization1(total_text):
    total_text = [lemmatizer.lemmatize(w, get_wordnet_pos(w)) for w in nltk.word_tokenize(total_text)]

    return total_text

In [13]:
trainS['text'] = trainS['text'].map(lemmatization1)
trainS.head(20)

,id,keyword,location,text,target
0,1,NaN,NaN,"[our, deed, be, the, reason, of, this, earthqu...",1
1,4,NaN,NaN,"[forest, fire, near, la, ronge, sask, canada]",1
2,5,NaN,NaN,"[all, resident, ask, to, 'shelter, in, place, ...",1
3,6,NaN,NaN,"[people, receive, wildfire, evacuation, order,...",1
4,7,NaN,NaN,"[just, get, sent, this, photo, from, ruby, ala...",1
5,8,NaN,NaN,"[rockyfire, update, california, hwy, close, in...",1
6,10,NaN,NaN,"[flood, disaster, heavy, rain, cause, flash, f...",1
7,13,NaN,NaN,"[i, be, on, top, of, the, hill, and, i, can, s...",1
8,14,NaN,NaN,"[there, be, an, emergency, evacuation, happen,...",1
9,15,NaN,NaN,"[i, be, afraid, that, the, tornado, be, come, ...",1
10,16,NaN,NaN,"[three, people, die, from, the, heat, wave, so...",1
11,17,NaN,NaN,"[haha, south, tampa, be, get, flood, hah, wait...",1
12,18,NaN,NaN,"[rain, flood, florida, tampabay, tampa, or, da...",1
13,19,NaN,NaN,"[flood, in, bago, myanmar, we, arrive, bago]",1
14,20,NaN,NaN,"[damage, to, school, bus, on, in, multi, car, ...",1
15,23,NaN,NaN,"[what, be, up, man]",0
16,24,NaN,NaN,"[i, love, fruit]",0
17,25,NaN,NaN,"[summer, be, lovely]",0
18,26,NaN,NaN,"[my, car, be, so, fast]",0
19,28,NaN,NaN,"[what, a, goooooooaaaaaal]",0

In [14]:
def justalpha(total_text):

    total_text = re.sub('\'', ' ', str(total_text))
       
    return total_text

In [15]:
trainS['text'] = trainS['text'].map(justalpha)
trainS.head(20)

,id,keyword,location,text,target
0,1,NaN,NaN,"[ our , deed , be , the , reason , of , ...",1
1,4,NaN,NaN,"[ forest , fire , near , la , ronge , sas...",1
2,5,NaN,NaN,"[ all , resident , ask , to , "" shelter"", ...",1
3,6,NaN,NaN,"[ people , receive , wildfire , evacuation ...",1
4,7,NaN,NaN,"[ just , get , sent , this , photo , from...",1
5,8,NaN,NaN,"[ rockyfire , update , california , hwy , ...",1
6,10,NaN,NaN,"[ flood , disaster , heavy , rain , cause ...",1
7,13,NaN,NaN,"[ i , be , on , top , of , the , hill , ...",1
8,14,NaN,NaN,"[ there , be , an , emergency , evacuation...",1
9,15,NaN,NaN,"[ i , be , afraid , that , the , tornado ...",1
10,16,NaN,NaN,"[ three , people , die , from , the , hea...",1
11,17,NaN,NaN,"[ haha , south , tampa , be , get , flood...",1
12,18,NaN,NaN,"[ rain , flood , florida , tampabay , tamp...",1
13,19,NaN,NaN,"[ flood , in , bago , myanmar , we , arri...",1
14,20,NaN,NaN,"[ damage , to , school , bus , on , in , ...",1
15,23,NaN,NaN,"[ what , be , up , man ]",0
16,24,NaN,NaN,"[ i , love , fruit ]",0
17,25,NaN,NaN,"[ summer , be , lovely ]",0
18,26,NaN,NaN,"[ my , car , be , so , fast ]",0
19,28,NaN,NaN,"[ what , a , goooooooaaaaaal ]",0

In [16]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [27]:
def remove_stopwords(total_text):
    
    filtered_word_list = total_text[:]
    for word in total_text:
        if word in stop_words: 
            filtered_word_list.remove(word)
    
    #filtered_sentence = [w for w in total_text if not w in stop_words] 
    #filtered_sentence= []
    
    #for w in total_text: 
      #  if w not in stop_words: 
       #     filtered_sentence.append(w) 

    return filtered_word_list

In [28]:
trainS['text'] = trainS['text'].map(remove_stopwords)
trainSR = trainS
trainSR.head(20)

,id,keyword,location,text,target
0,1,NaN,NaN,"[[, , u, r, , ,, , , e, e, , ,, , , b, ...",1
1,4,NaN,NaN,"[[, , f, r, e, , ,, , , f, r, e, , ,, , ...",1
2,5,NaN,NaN,"[[, , l, l, , ,, , , r, e, e, n, , ,, , ...",1
3,6,NaN,NaN,"[[, , p, e, p, l, e, , ,, , , r, e, c, e, ...",1
4,7,NaN,NaN,"[[, , j, u, , ,, , , g, e, , ,, , , e, ...",1
5,8,NaN,NaN,"[[, , r, c, k, f, r, e, , ,, , , u, p, e, ...",1
6,10,NaN,NaN,"[[, , f, l, , ,, , , e, r, , ,, , , h, ...",1
7,13,NaN,NaN,"[[, , , ,, , , b, e, , ,, , , n, , ,, ...",1
8,14,NaN,NaN,"[[, , h, e, r, e, , ,, , , b, e, , ,, , ...",1
9,15,NaN,NaN,"[[, , , ,, , , b, e, , ,, , , f, r, , ...",1
10,16,NaN,NaN,"[[, , h, r, e, e, , ,, , , p, e, p, l, e, ...",1
11,17,NaN,NaN,"[[, , h, h, , ,, , , u, h, , ,, , , p, ...",1
12,18,NaN,NaN,"[[, , r, n, , ,, , , f, l, , ,, , , f, ...",1
13,19,NaN,NaN,"[[, , f, l, , ,, , , n, , ,, , , b, g, ...",1
14,20,NaN,NaN,"[[, , g, e, , ,, , , , ,, , , c, h, l, ...",1
15,23,NaN,NaN,"[[, , w, h, , ,, , , b, e, , ,, , , u, ...",0
16,24,NaN,NaN,"[[, , , ,, , , l, v, e, , ,, , , f, r, ...",0
17,25,NaN,NaN,"[[, , u, e, r, , ,, , , b, e, , ,, , , ...",0
18,26,NaN,NaN,"[[, , , ,, , , c, r, , ,, , , b, e, , ...",0
19,28,NaN,NaN,"[[, , w, h, , ,, , , , ,, , , g, l, , ]]",0

In [ ]:
# Save to csv
 data.to_csv("clean.csv", index=False, encoding = 'utf-8')